Develop
idealista/prometheus_apache_exporter_role pull request #3
Opened 2017-11-15 12:46 UTC by jdvr

First release

2017-11-15 14:13 UTC, jnogol approved these changes

2017-11-16 11:18 UTC, jmonterrubio commented on README.md
> +![Logo](logo.gif)
Use full path ![Logo](https://raw.githubusercontent.com/idealista/apache_exporter-role/master/logo.gif)

2017-11-16 11:20 UTC, jmonterrubio commented on README.md
> +![Ansible](https://img.shields.io/badge/ansible-2.2.1.0-green.svg)
2.3, same as prerequisites version

2017-11-16 11:21 UTC, jmonterrubio commented on README.md
> +![Ansible](https://img.shields.io/badge/ansible-2.2.1.0-green.svg)
Also you could add:
![Molecule](https://img.shields.io/badge/molecule-1.25.0-green.svg)
![Testinfra](https://img.shields.io/badge/testinfra-1.9.0-green.svg)

2017-11-16 11:22 UTC, dortegau approved these changes

2017-11-16 11:26 UTC, jmonterrubio requested changes
Take a look to the readme comments

2017-11-16 11:47 UTC, jmonterrubio approved these changes

2017-11-16 11:48 UTC, merged